[versions]

kotlin     = "1.8.21"
coroutines = "1.7.0"
yass2      = "12.0.0"

[libraries]

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

yass2-core     = { module = "ch.softappeal.yass2:yass2-core"    , version.ref = "yass2" }
yass2-generate = { module = "ch.softappeal.yass2:yass2-generate", version.ref = "yass2" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
