[versions]

kotlin             = "2.0.21"
kotlinx-coroutines = "1.9.0"
yass2              = "16.1.0"

[libraries]

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

yass2-core     = { module = "ch.softappeal.yass2:yass2-core"     , version.ref = "yass2" }
yass2-generate = { module = "ch.softappeal.yass2:yass2-generate" , version.ref = "yass2" }

[plugins]

jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
