[versions]

kotlin     = "1.8.21"
ksp        = "1.8.21-1.0.11" # kotlin must be prefix of ksp
coroutines = "1.7.1"
yass2      = "13.0.0"

[libraries]

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

yass2-core     = { module = "ch.softappeal.yass2:yass2-core"    , version.ref = "yass2" }
yass2-generate = { module = "ch.softappeal.yass2:yass2-generate", version.ref = "yass2" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
