[versions]

kotlin = "2.0.21" # https://github.com/JetBrains/kotlin
kotlinx-coroutines = "1.9.0" # https://github.com/Kotlin/kotlinx.coroutines

[libraries]

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

[plugins]

jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
