#file: noinspection SpellCheckingInspection
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/actions/wrapper-validation@v4
      - run: |
          docker image     build                                        --tag project-image .
          docker container create              --name project-container       project-image ./gradlew -Pversion=`git describe`
          docker container start --interactive        project-container
          docker container cp                         project-container:/project/build/distributions .
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create `git describe` distributions/diff-`git describe`.zip
